---
branches:
  - main
  - name: develop
    prerelease: true
debug: true
ci: true
dryRun: false
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - ["@semantic-release/exec",
    {
      "successCmd": 'echo "SEMVER_VERSION=${nextRelease.version}" > $GITHUB_ENV',
    },]