name: Release
on:
  push:
    branches:
      - main
      - develop
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      # - name: Install dependencies
      #   run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: semantic_release
        run: npx semantic-release
      # - name: Check if version changed
      #   id: version_changed
      #   run: echo "{version_changed}={$(jq -r '.nextRelease.version != null' ${{ steps.semantic_release.outputs.releaseConfig }})}" >> $GITHUB_OUTPUT

      # - name: Set Version Environment Variable
      #   if: steps.version_changed.outputs.version_changed == 'true'
      #   run: |
      #     echo "RELEASE_VERSION=$(jq -r '.nextRelease.version' ${{ steps.semantic_release.outputs.releaseConfig }})" >> $GITHUB_ENV

      - name: Echo Release Version
        # if: steps.version_changed.outputs.version_changed == 'true'
        if: env.SEMVER_VERSION
        run: echo "The release version is ${{ env.SEMVER_VERSION }}"